- server/pom.xml
- server/src/main/kotlin/com/trib3/server/filters/RequestIdFilter.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLQuerySubscriber.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLWebSocket.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLWebSocketCreator.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLWebSocketProtocol.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketCreatorTest.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketProtocolTest.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketTest.kt
Support the apollo protocol to allow starting and
stopping queries and reuse of the websocket for multiple
queries.  Have the websocket track the running query and
try to execute only one at a time.  Skip implementing
keepalive heartbeats for now.
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md
Tested in https://github.com/prisma/graphql-playground
> Implement the apollo graphql subscription protocol

- server/README.md
- server/pom.xml
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLConfig.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLQuerySubscriber.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLWebSocket.kt
- server/src/main/kotlin/com/trib3/server/graphql/GraphQLWebSocketCreator.kt
- server/src/main/resources/reference.conf
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLConfigTest.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketCreatorTest.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketTest.kt
To prevent long running queries from timing out the socket,
send a keepalive packet every 15 seconds.
Execute the graphQL query within the rx context so that we
free up the webserver threads and don't hold locks for long.
> Implement keepalive for graphql websockets

- db/src/main/kotlin/com/trib3/db/converters/YearConverter.kt
- db/src/test/kotlin/com/trib3/db/converters/YearConverterTest.kt
- server/src/main/kotlin/com/trib3/server/graphql/DateTimeHooks.kt
- server/src/test/kotlin/com/trib3/server/graphql/DateTimeHooksTest.kt
Support serializing/deserializing java.time.Year objects
in the graphql and db layers
> Add graphql and jooq converters for java.time.Year

- .circleci/config.yml
Currently the github release name is the last commit
message first line.  Specify it as the version instead.
Also remove unneeded log line on websocket disconnect.
> Specify name in github release

- config/pom.xml
- config/src/test/kotlin/com/trib3/config/ExtensionTest.kt
- config/src/test/kotlin/com/trib3/config/KMSStringReaderTest.kt
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/kotlin/com/trib3/server/healthchecks/PingHealthCheck.kt
- server/src/main/kotlin/com/trib3/server/healthchecks/VersionHealthCheck.kt
- server/src/test/kotlin/com/trib3/server/TribeApplicationTest.kt
- server/src/test/kotlin/com/trib3/server/TribeServerlessTest.kt
- server/src/test/kotlin/com/trib3/server/config/dropwizard/FilteredRequestLogTest.kt
- server/src/test/kotlin/com/trib3/server/filters/AdminAuthFilterTest.kt
- server/src/test/kotlin/com/trib3/server/filters/RequestIdFilterTest.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketCreatorTest.kt
- server/src/test/kotlin/com/trib3/server/graphql/GraphQLWebSocketTest.kt
- testing/README.md
- testing/pom.xml
- testing/src/main/kotlin/com/trib3/testing/LeakyMock.kt
- testing/src/test/kotlin/com/trib3/testing/LeakyMockTest.kt
Add support for mocking without having to type the class
name twice using inline functions.  Also add support for
mock argument matchers that return non-null values to
avoid issues with mocked arguments to methods that don't
accept null arguments; this bit is more fragile as it
only works for open/non-final classes, but can help avoid
some of the `anyObject() ?: defaultValue` blocks that
show up in tests.
Also configure surefire to print stack traces when tests fail.
> Add mocking utility class

- parent-pom/pom.xml
Bumps `version.jetty` from 9.4.19.v20190610 to 9.4.20.v20190813.
Bumps `version.dropwizard` from 2.0.0-rc5 to 2.0.0-rc9.
Updates `dropwizard` from 2.0.0-rc5 to 2.0.0-rc9
- [Release notes](https://github.com/dropwizard/dropwizard/releases)
- [Commits](https://github.com/dropwizard/dropwizard/compare/v2.0.0-rc5...v2.0.0-rc9)
Updates `jetty-servlets` from 9.4.19.v20190610 to 9.4.20.v20190813
- [Release notes](https://github.com/eclipse/jetty.project/releases)
- [Commits](https://github.com/eclipse/jetty.project/compare/jetty-9.4.19.v20190610...jetty-9.4.20.v20190813)
Updates `jetty-server` from 9.4.19.v20190610 to 9.4.20.v20190813
- [Release notes](https://github.com/eclipse/jetty.project/releases)
- [Commits](https://github.com/eclipse/jetty.project/compare/jetty-9.4.19.v20190610...jetty-9.4 …
> Bump version.jetty from 9.4.19.v20190610 to 9.4.20.v20190813

- build-resources/src/main/resources/.ebextensions/elb.config
- build-resources/src/main/resources/.ebextensions/nginx/nginx.conf
ALB timeout uses a different setting than
classic ELBs, so set the timeout for those
as well
> Update ELB timeout for ALBs

- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- testing/src/main/kotlin/com/trib3/testing/LeakyMock.kt
- testing/src/test/kotlin/com/trib3/testing/LeakyMockTest.kt
Instead of requiring nested calls to and/or together
more than two expectations, use varargs to allow
for a call with multiple expectations at once.
(see GraphQLWebSocketTest for usage changes)
> Add vararg for LeakyMock.and() and or()

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketAdapter.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreator.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketAdapterTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/pom.xml
Instead of using GlobalScope, have the WebSocketAdapter
implement CoroutineScope and use that to control the
coroutines' lifecycles.  Separate out child coroutines
into their own classes that can only access the channel
and not the websocket for safety.  Also make the injected
graphQL instance non-nullable, as now that graphql is a
separate module services that don't want graphQL will
just not install the module.  Bump version to 1.6.x.
> Cleanup GraphQL coroutines implementation

- db/src/main/kotlin/com/trib3/db/config/DbConfig.kt
- db/src/test/kotlin/com/trib3/db/modules/DbModuleTest.kt
- db/src/test/resources/application.conf
Add the frequently used options from
https://github.com/brettwooldridge/HikariCP/#frequently-used
to DbConfig so that they can be set by application config
> Add Frequently Used HikariCP options to DbConfig

- graphql/src/main/kotlin/com/trib3/graphql/execution/CustomDataFetcherExceptionHandler.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
Subscription data events were missing the requestId extension
that we install.  Manually add them in to ensure we can trace
execution more easily.
https://trello.com/c/DHzkp35u
> Ensure RequestId comes back on subsription data events

- build-resources/pom.xml
- config/pom.xml
- config/src/main/kotlin/com/trib3/config/ConfigLoader.kt
- config/src/test/kotlin/com/trib3/config/ConfigLoaderTest.kt
- db/pom.xml
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/GraphQLConfig.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/test/kotlin/com/trib3/graphql/GraphQLConfigTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLUpgradeResourceTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreatorTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- graphql/src/test/resources/application.conf
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/kotlin/com/trib3/server/config/BootstrapConfig.kt
- server/src/test/kotlin/com/trib3/server/config/TribeApplicationConfigTest.kt
- server/src/test/kotlin/com/trib3/server/config/dropwizard/HoconConfigurationTest.kt
- testing/pom.xml
Let websocket policy timeouts and max messages sizes be
specfied in application config.
Adds convenience methods to ConfigLoader to allow eg. tests
to inject a ConfigLoader that sets a "defaultPath" which
acts similar to an environmental override, without having
the specific Config code needing to load through a path.
https://trello.com/c/lOjLKQi8/
> Allow configuration of websocket policy items

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/pom.xml
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/pom.xml
Graphql 2.0.0 release, flyway pom scope change, and
graphql hooks name change need a bump
> Bump version to 1.9

- db/README.md
- db/pom.xml
- db/src/main/kotlin/com/trib3/db/config/DbConfig.kt
- db/src/main/kotlin/com/trib3/db/flyway/FlywayBundle.kt
- db/src/main/kotlin/com/trib3/db/modules/FlywayModule.kt
- db/src/main/resources/reference.conf
- db/src/test/kotlin/com/trib3/db/flyway/FlywayBundleTest.kt
- db/src/test/kotlin/com/trib3/db/modules/FlywayModuleTest.kt
- db/src/test/kotlin/com/trib3/db/modules/NamedDbModuleTest.kt
- db/src/test/resources/application.conf
- graphql/README.md
- graphql/src/main/kotlin/com/trib3/graphql/execution/LeakyCauldronHooks.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/LeakyCauldronHooksTest.kt
- testing/src/main/kotlin/com/trib3/testing/db/DAOTestBase.kt
```
Add configuration for flyway and full jdbc url
Allow non-default Flyway configuration in tests via override and
at runtime via a new guice module.
Allow configuration via full jdbc url when running in, eg heroku.
```
```
Add UUID graphql scalar type
Support UUIDs in graphql queries as String representations.
Rename DateTimeHooks -> LeakyCauldronHooks since it's not all
DateTime related anymore.  Include a typealias for backward
compatiblity.
```
> Flyway config and UUID scalars

- db/pom.xml
- db/src/main/kotlin/com/trib3/db/jooqext/ResultQueryFlow.kt
- db/src/test/kotlin/com/trib3/db/jooqext/ResultQueryFlowTest.kt
For a ResultQuery<T>, add a consumeAsFlow() extension
method that:
- allows clients to consume a Flow<T>
- ensures that the underlying query Cursor gets close()d
on successful or unsuccessful completion
- monitors the coroutine execution for cancellation,
and calls query.cancel() to stop any synchronous JDBC
operations that are blocking execution
> Add jOOQ ResultQuery Flow adapter

- parent-pom/pom.xml
0.4.2 got removed from jcenter, which breaks all
builds without a cached copy of the artifact
> Bump config4k version back down to 0.4.1

- graphql/src/main/kotlin/com/trib3/graphql/execution/JsonSafeExecutionResultMixin.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/JsonSafeExecutionResultMixinTest.kt
- json/pom.xml
- json/src/main/kotlin/com/trib3/json/ObjectMapperProvider.kt
- json/src/main/kotlin/com/trib3/json/modules/ObjectMapperModule.kt
- json/src/test/kotlin/com/trib3/json/ObjectMapperTest.kt
According to the graphql spec, the data/errors/extensions
keys should exist in the json unless they have corresponding
data attached.  Some 3rd party tools like the js-graphql
plugin for jetbrains products fail to read the graphql
schema because of this deviation.  Use a jackson mixin in
order to serialize to json properly, and add the ability for
custom mixins to be injected into the ObjectMapper provider.
> Serialize graphql json according to spec

- db/src/main/kotlin/com/trib3/db/jooqext/ResultQueryFlow.kt
- db/src/test/kotlin/com/trib3/db/jooqext/ResultQueryFlowTest.kt
If the coroutine gets cancelled prior to the cleanup
monitor actually starting its work, the cleanup logic
will get skipped and the query cancellation won't happen.
This mostly affects the unit test which has been failing
sporadically because of this race condition
> Atomically start the cleanup monitor coroutine

- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/execution/GraphQLRequest.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/GraphQLApplicationModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreator.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreatorFactory.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/GraphQLRequestTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/modules/GraphQLApplicationModuleTest.kt
- lambda/src/main/kotlin/com/trib3/lambda/resources/AdminResource.kt
- parent-pom/pom.xml
- server/src/main/kotlin/com/trib3/server/healthchecks/VersionHealthCheck.kt
When dealing with graphs of objects, DataLoaders allow applications
to avoid having to issue N+1 queries to fetch relations of N objects.
Allow applications to configure DataLoaders by binding an implementation
of a DataLoaderRegistryFactory that will create a per request registry
of DataLoaders.
(See https://www.graphql-java.com/documentation/v14/batching/ for more
details)
Add a centralized method to convert GraphQLRequest objects into
ExecutionInput objects to avoid duplicating that logic between the
WebSocket and Resource endpoints.
Use let scope function for more fluent conditional builder usage.
> Bindings for GraphQL DataLoaderRegistry

- .editorconfig
- parent-pom/pom.xml
Explicitly manage the ktlint version instead of relying
on the transitive version of the ktlint-maven-plugin and
having to wait for another release.  With latest ktlint,
we can turn on the import ordering rule without conflicting
with IntelliJ's defaults, so do that.
> Bump ktlint from implicit 0.37.0 to explicit 0.37.1

- .circleci/config.yml
Latest version doesn't support setting version with
parent pom in a subdirectory, so use the last version
that worked.  Also better to specify version explicitly
than to automatically get latest version.
See https://github.com/mojohaus/versions-maven-plugin/issues/426
> Explicitly use maven versions plugin 2.7

- .circleci/config.yml
- README.md
- build-resources/pom.xml
- config/README.md
- graphql/README.md
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketProtocol.kt
- json/README.md
- parent-pom/pom.xml
- server/README.md
Update github links in README files to point
to `HEAD` (ie, whatever the default branch is),
and update circle to treat `main` as the main
branch to deploy to production.
> Change master references to main

- server/pom.xml
- server/src/main/kotlin/com/trib3/server/coroutine/CoroutineInvocationHandler.kt
- server/src/main/kotlin/com/trib3/server/coroutine/CoroutineModelProcessor.kt
- server/src/test/kotlin/com/trib3/server/coroutine/CoroutineInvocationHandlerTest.kt
- server/src/test/kotlin/com/trib3/server/coroutine/CoroutineModelProcessorTest.kt
- testing/src/main/kotlin/com/trib3/testing/server/ResourceTestBase.kt
When a resource is wrapped in an AOP dynamic subclass,
grab annotations from the definitionMethod instead of
the handlingMethod, and work around a reflection issue
by using `call(*args, continuation)` instead of
`callSuspending(*args)`.
Also use `type` instead of `rawType` to define method
parameters so that we don't lose generic type parameter
information.
> Fix coroutine jersey bugs with generics and AOP

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/README.md
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/execution/ContextScopeFunctionDataFetcher.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/ContextScopeFunctionDataFetcherTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- server/src/test/kotlin/com/trib3/server/coroutine/CoroutineInvocationHandlerTest.kt
- testing/pom.xml
- testing/src/main/kotlin/com/trib3/testing/server/ResourceTestBase.kt
- testing/src/test/kotlin/com/trib3/testing/server/ResourceTestBaseTest.kt
Run REST-based GraphQL queries as asynchronous coroutines, and
support an endpoint to cancel them by requestId.
Includes an implementation of FunctionDataFetcher that reads
coroutine scope from the GraphQL context to fix a structured
concurrency issue, see:
https://github.com/ExpediaGroup/graphql-kotlin/pull/879
Also default to use JettyWebTestContainerFactory in resource
tests since enough new functionality isn't supported by the
in-memory container.
(Breaking change, update version to 1.14.x)
> Cancellable async GraphQL execution

- build-resources/src/main/resources/assemblies/elasticbeanstalk.xml
In order to specify eg. jvm command line args, EBS
services need to provide a Procfile in the assembly zip.
This allows one to be added to source control in
`${projectDir}/server/Procfile`, filtered by maven for
eg. property value replacement, and included in the
final assembly.
> Allow Elastic BeanStalk services to include Procfiles

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/GraphQLConfig.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/resources/graphiql/index.html
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceIntegrationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- graphql/src/test/resources/application.conf
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/pom.xml
Allow services to enforce that all websocket clients
must be authenticated to connect.
Return a 401 Unauthorized when all GraphQL responses
are 401 Unauthorized.  Bump version to 1.16.x due to
behavior change.
Also update graphiql to latest version and support
subscriptions via subscriptions-transport-ws.
> GraphQL Authentication Tweaks

- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/GraphQLConfig.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- parent-pom/pom.xml
Hide the optional @Auth principals from swagger
documentation, as they break the construction of
the OpenAPI response
> Fix swagger in graphQL resource

- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/resources/graphiql/index.html
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceIntegrationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- server/src/main/kotlin/com/trib3/server/filters/AdminAuthFilter.kt
- server/src/main/kotlin/com/trib3/server/modules/DefaultApplicationModule.kt
- server/src/main/kotlin/com/trib3/server/resources/AuthCookieResource.kt
- server/src/main/resources/reference.conf
- server/src/test/kotlin/com/trib3/server/filters/AdminAuthFilterTest.kt
- server/src/test/kotlin/com/trib3/server/resources/AuthCookieResourceTest.kt
Add an endpoint to convert header based auth to cookie based auth,
and use in graphiql to authenticate the graphql websocket without
exposing the credentials directly to javascript code
> Add endpoint moving header based auth to a cookie

- parent-pom/pom.xml
- server/pom.xml
Silences a warning about javax.activation.DataSource
being missing from the classpath, and fixes downstream
projects that rely on activation (think this used to
be a transitive dependency that got removed)
> Add activation jar to server runtime

- .github/dependabot.yml
Going to wait on these until dropwizard takes them up,
so instruct dependabot to ignore those versions for now.
> Exclude jakarta ee 9 versions from dependabot

- parent-pom/pom.xml
Bumps `version.jetty` from 9.4.36.v20210114 to 9.4.37.v20210219.
Updates `jetty-bom` from 9.4.36.v20210114 to 9.4.37.v20210219
- [Release notes](https://github.com/eclipse/jetty.project/releases)
- [Commits](https://github.com/eclipse/jetty.project/compare/jetty-9.4.36.v20210114...jetty-9.4.37.v20210219)
Updates `jetty-server` from 9.4.36.v20210114 to 9.4.37.v20210219
- [Release notes](https://github.com/eclipse/jetty.project/releases)
- [Commits](https://github.com/eclipse/jetty.project/compare/jetty-9.4.36.v20210114...jetty-9.4.37.v20210219)
Updates `websocket-servlet` from 9.4.36.v20210114 to 9.4.37.v20210219
> Bump version.jetty from 9.4.36.v20210114 to 9.4.37.v20210219

- db/README.md
- db/pom.xml
- db/src/main/kotlin/com/trib3/db/config/DbConfig.kt
- db/src/test/kotlin/com/trib3/db/modules/NamedDbModuleTest.kt
- db/src/test/resources/application.conf
- parent-pom/pom.xml
adds a jooq settings block underneath the db settings block
to allow for setting of any jooq custom settings.
see https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/
> Allow jooq custom settings via DbConfig

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/pom.xml
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/pom.xml
com.sun...:jaxb-impl is replaced with org.glassfish..:jaxb-runtime
add com.sun one to banned dependencies and bump version.
Also set Multi-Release=true to avoid deprecated reflection warning
> Switch jaxb jar to the new one [Potentially breaking change]

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/execution/ContextScopeFunctionDataFetcher.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/LeakyCauldronHooks.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/SanitizedGraphQLError.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/LeakyCauldronHooksTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/RequestIdInstrumentationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceIntegrationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/pom.xml
Update package/class names to match upstream changes.
Bump version due to upstream breaking changes:
- addition of generator subpackage to graphql-kotlin
- ExecutionPath -> ResultPath in graphql-java
- selectionSet.fields behavior change in graphql-java
> Bump to graphql-kotlin 4.0.0/graphql-java 16.2 [Breaking changes]

- db/src/main/kotlin/com/trib3/db/converters/YearMonthConverter.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- json/README.md
- json/pom.xml
- json/src/main/kotlin/com/trib3/json/ObjectMapperProvider.kt
- json/src/main/kotlin/com/trib3/json/jackson/DontUseInputGuiceAnnotationIntrospector.kt
- json/src/test/kotlin/com/trib3/json/ObjectMapperTest.kt
- lambda/src/main/kotlin/com/trib3/lambda/resources/AdminResource.kt
- parent-pom/pom.xml
- server/README.md
- server/pom.xml
- server/src/main/kotlin/com/trib3/server/Extensions.kt
- server/src/main/kotlin/com/trib3/server/config/dropwizard/CloudWatchReporterFactory.kt
- server/src/main/kotlin/com/trib3/server/healthchecks/VersionHealthCheck.kt
- server/src/main/kotlin/com/trib3/server/resources/AuthCookieResource.kt
- server/src/main/resources/META-INF/services/io.dropwizard.metrics.ReporterFactory
- server/src/test/kotlin/com/trib3/server/ExtensionsTest.kt
- server/src/test/kotlin/com/trib3/server/config/dropwizard/CloudWatchReporterFactoryTest.kt
- server/src/test/resources/application.conf
Add a ReporterFactory that allows configuration of a
dropwizard-metrics-cloudwatch reporter with all
currently supported options.
Add a jackson-guice bridge to the ObjectMapperProvider
to allow for @JacksonInject to inject guice bound values
to deserialized json objects.
Add an extension function to make builder-like patterns
a little more usable.
> Add cloudwatch metrics reporter configuration

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/README.md
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/execution/GraphQLAuthDirectiveWiring.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/LeakyCauldronHooks.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/GraphQLApplicationModule.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/GraphQLAuthDirectiveWiringTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/LeakyCauldronHooksTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/RequestIdInstrumentationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/README.md
- server/pom.xml
- server/src/main/kotlin/com/trib3/server/modules/DefaultApplicationModule.kt
- server/src/main/kotlin/com/trib3/server/modules/TribeApplicationModule.kt
- testing/pom.xml
Add a schema directive that allows GraphQL schema fields
to be protected by role based auth.  Any field annotated
with @GraphQLAuth will only be returned to authenticated
users.  If an Authorizer binding is provided, then roles
passed to the @GraphQLAuth annotation will be enforced.
Bump version due to the Authorizer optional binding being
added by default, which may conflict with any existing
Authorizer bindings downstream.
Fix graphql tests to not scan the entire classpath,
saving memory when running tests.
> @GraphQLAuth directive [POSSIBLE BREAKING CHANGE]

- parent-pom/pom.xml
Transitively pulled in version of commons-compress has security
bugs, manage the version directly to avoid it.
> Manage commons-compress version to avoid vulnerabilities

- .circleci/config.yml
- build-resources/pom.xml
- config/pom.xml
- config/src/test/kotlin/com/trib3/config/modules/KMSModuleTest.kt
- db/pom.xml
- graphql/pom.xml
- json/pom.xml
- lambda/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/README.md
- testing/pom.xml
- testing/src/main/kotlin/com/trib3/testing/db/DAOTestBase.kt
Stands up docker based postgres db instead of a
process based one, which should work on eg, M1.
Requires using a machine circle image instad of
a docker circle image, so bump version.
Clean up KMSModuleTest to ensure a mock KMS gets
used to prevent ordering issue resulting in a real
KMS getting used in tests in some cases.
> Use TestContainers instead of otj-pg-embedded [BREAKING CHANGE] 

- graphql/README.md
- graphql/src/main/kotlin/com/trib3/graphql/GraphQLConfig.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/MessageGraphQLError.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketAdapter.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreator.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketProtocol.kt
- graphql/src/main/resources/graphiql/index.html
- graphql/src/main/resources/reference.conf
- graphql/src/test/kotlin/com/trib3/graphql/GraphQLConfigTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketAdapterTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreatorTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketProtocolTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- graphql/src/test/resources/application.conf
The existing subscriptions-transport-ws protocol is deprecated.
Introduce the new protocol by mapping operations and adhering
to the stricter semantics of the new protocol.  Update embedded
GraphiQL to use the new protocol.
Use existing tests to cover most corner cases, but add tests
of the new protocol's stricter semantics in addition to testing
the basic subscription workflow.
> Support new graphql-ws websocket protocol

- graphql/README.md
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/GraphQLConfig.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/ContextScopeFunctionDataFetcher.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/GraphQLAuthDirectiveWiring.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/GraphQLRequest.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/LeakyCauldronHooks.kt
- graphql/src/main/kotlin/com/trib3/graphql/execution/MessageGraphQLError.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/GraphQLApplicationModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketAdapter.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreator.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketProtocol.kt
- graphql/src/main/resources/graphiql/index.html
- graphql/src/main/resources/reference.conf
- graphql/src/test/kotlin/com/trib3/graphql/GraphQLConfigTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/ContextScopeFunctionDataFetcherTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/GraphQLAuthDirectiveWiringTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/GraphQLRequestTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/LeakyCauldronHooksTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceIntegrationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketAdapterTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketCreatorTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketProtocolTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
- graphql/src/test/resources/application.conf
- parent-pom/pom.xml
The graphql-kotlin GraphQLContext interface is deprecated
and replaced with a new class from graphql-java that's backed
by a Map<*, Any>.  Adjust our context for this change.
Also some scalars are removed and moved to an -extended-scalars
package, use that for BigDecimal support.  Might want to use
more of the provided scalars in the future?
> Port to graphql-kotlin 5 / graphql-java 17 [BREAKING CHANGE]

- graphql/src/main/resources/graphiql/index.html
The query to get schema from the server is executed with the
documentAST set to the editor pane's query instead of an AST
from the introspection query itself, and the subscription that
the fetcher returns is set up for the UI, not for internal code.
Ensure we always use a standard HTTP fetcher for the introspection
query so that the schema explorer loads properly.
https://www.notion.so/tribedynamics/Pebbles-Auto-Fill-and-Documentation-Helper-are-not-Loading-b5fc5f98a9a14c56bc74f3a85025e658
> Fix GraphiQL's schema explorer when using subscriptions

- graphql/src/main/kotlin/com/trib3/graphql/execution/ContextScopeFunctionDataFetcher.kt
- graphql/src/main/resources/graphiql/index.html
In GraphiQL, use the WebSocket connection to execute queries
in addition to subscriptions, so that long running queries
don't get killed by the load balancer.  Leave mutations on a
normal HTTP connection so that they can set cookies.
Add MDCContext when calling suspend functions from a GraphQL
resolver so that requestId gets picked up by the instrumentation.
> Execute GraphiQL queries using WebSocket connection

- graphql/src/main/resources/graphiql/index.html
Was not including operationName, so if multiple queries were
in the graphQL document the appropriate operation would not be
executed.  Just use the full graphQLParams object so we don't
miss any parameters
> Include full graphQLParams object in subscriptions

- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
Use a CountDownLatch to make sure the graphql channel
messages have been fully processed before verifying
mock expectations.
> Try to fix flaky test failure

- .circleci/config.yml
- graphql/README.md
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/execution/GraphQLRequest.kt
- graphql/src/main/kotlin/com/trib3/graphql/modules/DefaultGraphQLModule.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLResource.kt
- graphql/src/main/kotlin/com/trib3/graphql/resources/GraphQLSseResource.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketProtocol.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLResourceIntegrationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLSseResourceIntegrationTest.kt
- graphql/src/test/kotlin/com/trib3/graphql/resources/GraphQLSseResourceTest.kt
- graphql/src/test/resources/application.conf
- parent-pom/pom.xml
- server/pom.xml
- server/src/main/kotlin/com/trib3/server/coroutine/CoroutineInvocationHandler.kt
- server/src/main/kotlin/com/trib3/server/coroutine/CoroutineModelProcessor.kt
- server/src/main/resources/reference.conf
- server/src/test/kotlin/com/trib3/server/coroutine/CoroutineInvocationHandlerTest.kt
- server/src/test/kotlin/com/trib3/server/coroutine/CoroutineModelProcessorTest.kt
Allow for processing [graphql requests over SSE](https://github.com/enisdenjo/graphql-sse/blob/master/PROTOCOL.md), both in
'single connection mode' and 'distinct connections mode'
at the /app/graphql/stream endpoint.
Update jersey coroutine support to get method return types
correct and cancel running coroutines on client disconnect.
> Add support for graphql-sse protocols

- build-resources/pom.xml
- config/pom.xml
- db/pom.xml
- graphql/pom.xml
- graphql/src/main/kotlin/com/trib3/graphql/execution/LeakyCauldronHooks.kt
- graphql/src/test/kotlin/com/trib3/graphql/execution/LeakyCauldronHooksTest.kt
- json/pom.xml
- parent-pom/pom.xml
- pom.xml
- server/pom.xml
- testing/pom.xml
For UUID and date/time/datetime types, use available upstream
implementations instead of maintaining our own.  Note that
the `OffsetDateTime` GraphQL type is renamed to `DateTime`,
and the `LocalDate` GraphQL type is renamed to `Date`.  Serialized
datetimes will also better conform to ISO/RFC formats.
Also update our scalar implementations to throw the appropriate
exception type, resulting in queries that execute and return
error results instead of failing to execute.  This is compatible
with the graphql-java-extended-scalars implementations and more
in line with how GraphQL failures should be handled anyway.
Bump to version 1.31.x due to these behavioral changes.
> Use graphql-java-extended-scalars implementations [BREAKING CHANGE]

- parent-pom/pom.xml
This reverts commit 96d88784d87ff77f2f1a3748d36936ff4ccb5b7f.
Go back to 3.0.0-M3 since seeing spurious dependency convergence
errors when using version ranges: https://issues.apache.org/jira/browse/MENFORCER-426
> Revert "Bump maven-enforcer-plugin from 3.0.0-M3 to 3.1.0"

- graphql/src/main/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketConsumer.kt
- graphql/src/test/kotlin/com/trib3/graphql/websocket/GraphQLWebSocketTest.kt
When executing a query over the websocket transport, we were not getting requestIds back because things were executing in the CoroutineScope of the connection, which didn't yet have the requestId set on it.  Changing to execute in a child CoroutineScope that does have the requestId set via MDCContext() fixes the issue.
Modify the existing query-over-websocket test to
validate the query id gets set as the requestId.
> Fix coroutine requestId propogation

- graphql/src/main/resources/graphiql/index.html
- server/README.md
Update bundled graphiql, graphql-ws, and react to latest versions
> Bump graphiql to 2.2.0

- server/src/main/kotlin/com/trib3/server/config/TribeApplicationConfig.kt
- server/src/main/kotlin/com/trib3/server/modules/DefaultApplicationModule.kt
- server/src/main/resources/reference.conf
- server/src/test/kotlin/com/trib3/server/modules/DefaultApplicationModuleTest.kt
- Create new HeadersFilter for HTTP security headers
- Add headers to the reference.conf file
- Add headers to the appConfig
- Add provider for HeadersFilter that reads config, prepends "Set " and creates CSV list for Jetty HeadersFilter
Notion: https://www.notion.so/tribedynamics/Security-Vulnerability-Website-does-not-implement-X-Content-Type-Options-Best-Practices-88c12df26f2b4eb99f523c1e394b1099
> [BUG] Create HeadersFilter for HTTPS Security Headers

- parent-pom/pom.xml
Changed namespace means dependabot doesn't pick this up, so update manually
> Update git-commit-id maven plugin to 6.0.0

- parent-pom/pom.xml
Sonatype (part of the opensource system we use) alerted us to some security issues with the current version of logback since this is a minor version change I want to bump this now to be pulled in as part of the pebbles 3.0 bump.
> Bump Logback for security issues
